# Generated by Django 5.1.7 on 2025-04-07 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloadxml", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("satellite", models.CharField(max_length=4)),
                ("antenna", models.CharField(max_length=100)),
                ("orbit_num", models.IntegerField(default=0)),
                (
                    "utc_start_time",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 4, 7, 15, 30, 48, 116824)
                    ),
                ),
                ("source_file", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="XmlItem",
        ),
    ]
