# Generated by Django 5.1.7 on 2025-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloadxml", "0002_passitem_delete_xmlitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passitem",
            name="utc_start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
